import pygame
pygame.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2
BOARDER_WIDTH = 4

TEXT_FONT = pygame.font.Font("fonts/Pixeltype.ttf", 30)
TEXT_COLOR = "#E9F5EF"
BAR_COLOR = "#E9F5EF"

STARTING_POS = {
    "x" : SCREEN_WIDTH / 2,
    "y" : SCREEN_HEIGHT / 2,
}

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STAMINA = 100
