import pygame
pygame.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2
BOARDER_WIDTH = 4

TEXT_FONT = pygame.font.Font("fonts/Pixeltype.ttf", 30)
MENU_TEXT_FONT = pygame.font.Font("fonts/Pixeltype.ttf", 55)
TEXT_COLOR = "#E9F5EF"
BAR_COLOR = "#E9F5EF"

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STAMINA = 100
PLAYER_LIVES = 3
PLAYER_IMMUNITY_DURATION = 1500

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS