SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
LINE_WIDTH = 2
BOARDER_WIDTH = 4

STARTING_POS = {
    "x" : SCREEN_WIDTH / 2,
    "y" : SCREEN_HEIGHT / 2,
}

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STAMINA = 2
