import pygame

pygame.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

LEFT = -20
RIGHT = SCREEN_WIDTH + 20
TOP = -20
BOTTOM = SCREEN_HEIGHT + 20

PLAYER_RADIUS = 20
LINE_WIDTH = 2
BOARDER_WIDTH = 4

TEXT_FONT = pygame.font.Font("fonts/Pixeltype.ttf", 30)
MENU_TEXT_FONT = pygame.font.Font("fonts/Pixeltype.ttf", 55)
TEXT_COLOR = "#E9F5EF"
BAR_COLOR = "#E9F5EF"

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STAMINA = 100
PLAYER_LIVES = 3
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_BOMB_COOLDOWN_SECONDS = 1
PLAYER_IMMUNITY_DURATION = 1500

X = SCREEN_WIDTH / 2
Y = SCREEN_HEIGHT / 2
    
    
SHOT_RADIUS = 5 
BOMB_RADIUS = 15

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# 100 points if asteroid is more than or equal to (>=) max_radius
ASTEROID_MAX_POINTS = 100 
# 50 points if asteroid is less than max_radius
ASTEROID_MED_POINTS = 50 
# 25 points if asteroid radius is 20
ASTEROID_MIN_POINTS = 25 